
# Returns solution object given raw_data input from excel workbook

#' Find lowest cost industry pathway based on input parameters and assumptions
#'
#' Creates and runs a linear programming model that finds an optimal solution
#' (minimized cost) for UK industry's pathway to 2050.
#'
#' @param raw_data list of all input data, produced by [read_excel_data_template()]
#'  which is used to formulate the model and create all decision variables and
#'  constraints.
#' @param in_app boolean, set to TRUE if running the function from the Rshiny
#'  app. This allows the progress bar to be updated as the code progresses.
#'
#' @return list of length 4, which contains:
#'  * solution - a list containing the model solution, produced by [ROI_solve()]
#'  * data - a list of data tables that is used to create the model
#'  * decision_variables - a sparse matrix of the decision variables used by the model
#'  * PV_coefficients - list of model coefficients
#' @export
comit_solver <- function(raw_data, in_app = FALSE) {

  comit_tic('total for comit_solver')
  gc(verbose = FALSE) # Free up some storage

  data <- comit_preprocess_inputs(raw_data, in_app)

  objective_function <- comit_objective_function(data, in_app)

  decision_variables <- objective_function[[1]]
  PV_coefficients <- objective_function[[2]]

  rm(objective_function) # Free up storage
  gc()

  constraints <- comit_constraints(data, decision_variables, in_app)

  gc(verbose = FALSE)

  solved <- comit_problem_solver(data,
                                 decision_variables,
                                 PV_coefficients,
                                 constraints,
                                 in_app)

  comit_toc()

  return(solved)
}


## Helper functions ####--------------------------------------------------------

#' Perform the required data manipulation on the raw data
#'
#' Preprocesses the data required for the comit model, calling a series of other
#' functions:
#'  * `process_sites()`
#'  * `interpolate_data()`
#'  * `tidy()`
#'  * `round_years()`
#'  * `adjust_for_optimism()`
#'  * `apply_energy_efficiency()`
#'  * `adjust_existing_capacity()`
#'  * `add_site_ID()`
#'  * `assign_site_region()`
#'  * `add_H2_plants()`
#'  * `creat_H2_conversion()`
#'  * `site_demand()`
#'  * `site_H2C02_transport()`
#'
#' @inheritParams comit_solver
#'
#' @return list of all data tables for the input parameters, as provided by input
#'  parameter raw_data, now cleaned and ready to be used to specify model
#'  parameters.
#' @export
comit_preprocess_inputs <- function(raw_data,
                                    in_app = FALSE,
                                    counterfactual = FALSE) {

  comit_tic('data manipulation')
  message("Cleaning data")

  data <- raw_data %>%
    process_sites()

  data %<>%
    interpolate_data() %>%                  # expand data tables into yearly data if required
    tidy() %>%                              # turn data into tidy data
    round_years() %>%                       # round technology start year and lifetimes to nearest multiple of 5
    adjust_for_optimism() %>%               # uplift capex costs to account for optimism in prices
    apply_energy_efficiency() %>%           # reduce demand by energy efficiency values
    adjust_existing_capacity() %>%          # if required, increase existing capacity of technologies in the base year
    add_site_ID()                           # add unique id number to each site

  # add region variable
  data$NAEI_clean %<>% assign_site_region()

  # depending on whether H2 production is being explicitly modeled or not, we need to further adjust data
  data %<>%
    add_H2_plants(data$model_parameters$model_H2_production) %>%
    create_H2_conversion(data$model_parameters$model_H2_production)

  # work out demand at each site, in each year
  data$site_demand <- site_demand(data, counterfactual)

  # work out cheapest transport option for each site
  data$site_H2C02_transport <- site_H2C02_transport(data)

  comit_toc()
  progress_updater('data manipulation', in_app, data)

  return(data)
}



#' Generate decision variables and coefficients for the comit linear programming
#' model
#'
#' Create the data required to set up the comit objective function by creating
#'  the tables for decision variables and coefficients.
#'
#' @param data list of tables generated by preprocessing the raw inputs from the
#'  input spreadsheet using `comit_preprocess_inputs()`
#' @inheritParams comit_solver
#'
#' @return list of length two. The first element is a dataframe comprising
#'  the decision variables, as produced by create_decision_variables(). The
#'  second element is a dataframe for the coefficients for the objective function
#'  produced by the present value functions.
#' @export
comit_objective_function <- function(data, in_app = FALSE) {

  comit_tic('Setting objective function and decision variables')
  message("Creating decision variables")

  # temp drop new description column until new refactored code implemented
  data$objective_function %<>% select(!description)

  decision_variables <- create_decision_variables(data)

  # Get present value coefficients of decision variables for each linear term of the objective function
  message("Calculating costs")

  present_value_functions <- get_pv_functions(data)

  PV_coefficients <-
    lapply(present_value_functions, function(x) {
      do.call(get(x),
              list(data = data, decision_variables = decision_variables))
    }) %>%
    set_names(present_value_functions) %>%
    sum_PV_coefficients(n_decision_variables = nrow(decision_variables))

  comit_toc()
  progress_updater('Setting objective function and decision variables', in_app,
                   data)

  return(list(decision_variables, PV_coefficients))
}



#' Produce the constraints for the comit linear programme
#'
#' Sets up and combines all the constraints required for the linear programming
#'  model. Uses the following functions:
#'  * `get_constraint_functions()`
#'  * `run_constraint_function()`
#'  * `combine_matrix_constraints()`
#'
#' @param decision_variables dataframe for the decision variables. This is the
#'  first element of the list produced by `comit_objective_function`.
#' @inheritParams comit_objective_function
#'
#' @return List of length 3. The first element contains the direction for each
#'  constraint (==, <=, or >=). The second element contains the right hand side
#'  values. The third element contains the large simple triplet matrix, which
#'  contains the non-zero coeffecients for decision variables for each constraint.
#'
#' @export
comit_constraints <- function(data, decision_variables, in_app = FALSE) {

  comit_tic('setting constraints')

  constraint_functions <- get_constraint_functions(data)

  constraints <- lapply(constraint_functions,
                        run_constraint_function,
                        data,
                        decision_variables,
                        in_app)

  comit_toc()
  progress_updater('setting constraints', in_app, data)

  comit_tic('combining constraints')

  constraints %<>% combine_matrix_constraints()

  comit_toc()
  progress_updater('combining constraints', in_app, data)

  return(constraints)
}



#' Solve the comit optimization problem and return the results
#'
#' The problem is solved using ROI_solve or HiGHS (depending on the problem)
#'  and results are returned along with the input values. If the minimum
#'  available capacity of H2 plants is set to 0 (the default) in the input
#'  parameters, the problem is solved using linear programming, otherwise the
#'  problem is solved using mixed-integer linear programming (MILP).
#'
#' @param PV_coefficients dataframe for the objective function coefficients
#'  produced by `comit_objective_function`.
#' @param constraints dataframe for the constraints produced by
#'  `comit_objective_function`.
#' @inheritParams comit_constraints
#'
#' @return list of length four. The first element is the solution as produced by
#'  [`ROI_solve()`].The second element is the list of data as included in the input.
#'  The third and fourth elements are the decision variables and coefficients
#'  respectively, as produced by [`comit_objective_function()`].
#'
#' @export
comit_problem_solver <- function(data, decision_variables, PV_coefficients,
                                 constraints, in_app = FALSE) {

  comit_tic('solving problem')

  # check whether we constraint h2 size, if so we use a MILP solver (this is much slower!)
  constrain_hydrogen_plant_size <- data$constraints_to_include$include[
    data$constraints_to_include$constraint == 'minimum_hydrogen_plant_size']

  # define variable type (continuous, integer, or binary)
  if (constrain_hydrogen_plant_size) {

    variable_types <-
      if_else(substr(decision_variables$variable_type, 1, 2) == "b_",
              "B",
              "C")

    # Formulate problem and Solve
    problem <- OP(objective = L_objective(PV_coefficients$coefficient),
                  constraints = L_constraint(L = constraints$matr,
                                             dir = constraints$directions,
                                             rhs = constraints$rhs),
                  types = variable_types)

    message("Solving problem")
    solution <- ROI_solve(problem, solver = 'lpsolve', control = list())

    print(solution)

    # add solver name to allow for check later
    solution$solver <- 'lpsolve'

  } else { # this is what is ordinarily used

    message("Solving problem")
    solution <- comit_highs_solver(data, PV_coefficients, constraints)

  }

  solved <- list(solution = solution,
                 data = data,
                 decision_variables = decision_variables,
                 PV_coefficients = PV_coefficients)

  comit_toc()
  progress_updater('solving problem', in_app, data)

  return(solved)
}




comit_highs_solver <- function(data, PV_coefficients, constraints) {

  # Problem size
  n_vars <- nrow(PV_coefficients)
  n_cons <- length(constraints$directions)

  # Variable bounds
  lower <- rep(0, n_vars)
  upper <- rep(Inf, n_vars)


  sense <- constraints$directions
  rhs_val <- constraints$rhs

  # NOTE:
  # we define the problem slightly differently in highs. All constraints are in the form
  # lhs <= x <= rhs. So we need to provide both lhs and rhs values and rearrange things
  # slightly based on the specified direction.

  lhs <- numeric(length(sense))
  rhs <- numeric(length(sense))

  for (i in seq_along(sense)) {

    if (sense[i] == "<=") {
      lhs[i] <- -Inf
      rhs[i] <- rhs_val[i]
    } else if (sense[i] == ">=") {
      lhs[i] <- rhs_val[i]
      rhs[i] <- Inf
    } else if (sense[i] == "==") {
      lhs[i] <- rhs_val[i]
      rhs[i] <- rhs_val[i]
    }
  }

  # Set extremely small values to 0!
  # Values less than eps are just imprecise 0s that will make the model unstable
  eps <- 1e-12
  lhs[abs(lhs) < eps] <- 0
  rhs[abs(rhs) < eps] <- 0

  # use different solve method based on model type
  quickest_solver <- if(data$model_parameters$timestep >= 5) 'simplex' else 'ipm'

  result <- highs_solve(
    L = PV_coefficients$coefficient,
    A = constraints$matr,
    lhs = lhs,
    rhs = rhs,
    lower = lower,
    upper = upper,
    maximum = FALSE,
    control = list(solver = quickest_solver
                   #log_to_console = TRUE # For use in development
                   )
  )

  message(
    paste0(
      'Solution status: ', result$status_message, '\n',
      'Objective function value: ', round(result$objective_value, 0))
  )

  solution <- list(
    solution = result$primal_solution,
    objective_value = result$objective_value,
    status_message = result$status_message,
    solver = 'highs',
    solve_method = quickest_solver
  )

  return(solution)

}



#-------------------------------------------------------------------------------

#' Read in the standard version of the input data template
#'
#' This allows for quick running whilst developing and isn't exported as part
#' of the package.
#'
#' @param testing boolean for whether the code is being ran as part of formal tests,
#' in order to account for filepath change.
#'
#' @return list of all input data tables
standard_data_read <- function(testing = FALSE){

  # set in_app parameter globally for ease when developing
  in_app <<- FALSE

  raw_data <- read_excel_data_template(
    paste0(
      {if(testing) '../../' else ''},
      "data_template_archive/comit_input_1_4_0_public.xlsx"
      ))

  return(raw_data)
}



