# Functions for calculating emissions

#' Calculate the emissions per unit of production for technology variables
#'
#' Calculate the emissions per one unit of production for a given technology in
#'  a given year. Parameters are used to specify what is included or excluded in
#'  the emissions calculation.
#'
#' @param technology_code either a string or a character vector, of UKTM technology
#'  codes.
#' @param year either an integer or a vector of integers for the year which
#'  emissions of a technology are to be calculated. Emissions can vary by year
#'  due to fuel emissions changing over time for some fuels.
#' @param gas character: 'CO2', 'nonCO2' or NULL (default). Indicates what type
#'  of emission gas should be included. When NULL, both CO2 and non-CO2 gasses
#'  are counted.
#' @param source character: 'process', 'fuel' or NULL (default). Indicates what
#'  source of emissions should be counted. When NULL, both process and fuel
#'  sourced emissions are counted.
#' @param capture boolean, default is NULL. Indicates whether the emissions that
#'  are counted are those that are captured or not captured (i.e. released). When
#'  NULL, both captured and not-captured emissions are counted.
#' @param zero_emissions_from_biomass boolean, default is TRUE. Whether to treat
#'  biomass fuels as having 0 emissions.
#' @param location character: 'direct', 'indirect' or NULL (default). Indicates
#'  whether to count direct or indirect emissions. When NULL, both direct and
#'  indirect emissions are counted.
#' @param .data list of tables generated by preprocessing the raw inputs from the
#'  input spreadsheet using `comit_preprocess_inputs()`. Default is the object
#'  named 'data' which is used throughout comit code as the list of input tables.
#'
#' @returns numeric, emissions in kilotonnes of CO2e for the specified technologies
#'  and years.
#' @export
get_emissions <- function(technology_code,
                          year,
                          gas = NULL,
                          source = NULL,
                          capture = NULL,
                          zero_emissions_from_biomass = TRUE,
                          location = NULL,
                          .data = data) {

  # note that technology_code and year can be provided as vectors and can be
  # a column of a dataframe. All other parameters cannot be columns of a dataframe
  # due to the way this function works.

  # check arguments and set defaults
  gas_allowed <- c("CO2", "nonCO2")
  source_allowed <- c("process", "fuel")
  capture_allowed <- c(TRUE, FALSE)
  zero_emissions_from_biomass_allowed <- c(TRUE, FALSE)
  location_allowed <- c("direct", "indirect")

  gas_included <- check_emissions_param('gas', gas, gas_allowed)
  source_included <- check_emissions_param('source', source, source_allowed)
  capture_included <- check_emissions_param('capture', capture, capture_allowed)
  location_included <- check_emissions_param('location', location, location_allowed)

  zero_emissions_from_biomass <- check_emissions_param(
    'zero_emissions_from_biomass',
    zero_emissions_from_biomass,
    zero_emissions_from_biomass_allowed)

  # Year check is different as its numeric
  if (!is.numeric(year)) {
    stop(paste("argument year in 'get_emissions()' must be be of type numeric, not",
               class(year)))
  }

  emissions_df <- create_emissions_df(.data, technology_code, year)

  emissions_df <- emissions_df %>%
    recode_fuel_CO2e(., zero_emissions_from_biomass)


  # resolve missingness for required variables
  emissions_df %<>%
    replace_na(list(process_emission = FALSE,
                    proportion_emissions_CO2 = 0))

  emissions_df <- emissions_df %>%
    calculate_CO2_direct_emissions(.) %>%
    calculate_nonCO2_direct_emissions(.) %>%
    calculate_CO2_indirect_emissions(.) %>%
    calculate_nonCO2_indirect_emissions(.)


  aggregated_emissions <- sum_emission_types(emissions_df)

  total_emissions <- get_total_emissions(
    aggregated_emissions,
    gas_included,
    source_included,
    capture_included,
    location_included
  )

  # Left join emissions data to our original inputs to ensure order maintained
  output <- tibble(code = technology_code,
                   year = year) %>%
    left_join(total_emissions,
              by = c("code", "year")) %>%
    pull(CO2e)

  return(output)
}



#' Check that parameters provided to get_emissions() are allowed values
#'
#' @param emissions_param string, name of the parameter to check.
#' @param emissions_arg string, the value passed as a parameter to `get_emissions()`.
#' @param allowed_args character vector, the values allowed in this parameter.
#'
#' @returns the argument as provided, unless the emissions_arg parameter is NULL
#'  in which case the vector of allowed values is returned. Will raise an error
#'  if an invalid value is provided as emissions_arg.
check_emissions_param <- function(emissions_param, emissions_arg, allowed_args) {

  # do not test if no argument provided, just return the allowed arguments
  if (is.null(emissions_arg) & emissions_param != 'zero_emissions_from_biomass') {
    return(allowed_args)
    }

  # some params should be logical so slightly different check
  if (emissions_param %in% c('capture', "zero_emissions_from_biomass")
      & !is.logical(emissions_arg)) {
    stop(paste0("argument *", emissions_param,
                "* in get_emissions() must be be of type logical, not ",
                class(emissions_arg)))
  }

  # all other params
  if (!emissions_arg %in% allowed_args) {

    stop(paste0('argument *', emissions_param, '* in get_emissions() must be one of "',
                paste(allowed_args, collapse = '", "'),
                '" not "', emissions_arg, '"'))
  }

  # if above tests don't apply, just return as provided as input param
  return(emissions_arg)

}




#' Create a dataframe with required information to calculate emissions
#'
#' Creates a table for the relevant technologies and years, with all required
#'  data to calculate emissions using the function `get_emissions()`.
#'
#' @inheritParams get_emissions
#'
#' @returns dataframe, with one row per relevant commodity for distinct
#'  combinations of technology and year provided as parameters. Columns include:
#'  * code - character
#'  * year - numeric
#'  * commodity - character
#'  * output - amount of commodity produced/used by the technology to produce
#'   a single unit of output.
#'  * commodity_produces_emissions - boolean
#'  * proportion_emissions_CO2 - the proportion of emissions that are CO2 (as
#'   opposed to non-CO2 emissions).
#'  * process_emission - boolean
#'  * commodity_category - character
#'  * fuel_CO2e - numeric, the amount of emissions per unit of fuel used.
#'  * emissions_released - the proportion of emissions released by the technology,
#'   i.e. the proportion not captured.
#'  * direct_commodity - boolean, whether the commodity has direct (TRUE) or
#'   INDIRECT (FALSE) emissions.
#'
#' @export
create_emissions_df <- function(.data, technology_code, year) {

  # define commodities which produce indirect emissions
  indirect_commodities <- c("INDDISTELC",
                            "INDMAINSHYG",
                            "INDMAINSHYGG",
                            "INDMAINSHYGB")

  ## get data required to calculate emissions
  technology_input_output <- .data$technology_input_output %>%
    select(!c(primary_commodity,
              `technology description`,
              `commodity description`))

  commodities <- .data$commodities %>%
    select(commodity, proportion_emissions_CO2,
           process_emission, commodity_category)

  technologies <- .data$Technologies %>%
    select(code, emissions_released)

  fuel_emissions <- .data$Fuel_emissions %>%
    rename(fuel_CO2e = CO2e)


  emissions_df <- tibble(code = technology_code,
                         year = year) %>%
    distinct() %>%
    left_join(technology_input_output, by = c("code" = "technology_code")) %>%
    left_join(commodities, by = "commodity") %>%
    left_join(fuel_emissions, by = c("year", "commodity")) %>% # join in fuel emission factors for specified year
    left_join(technologies, by = "code") %>%  # add in capture rate
    mutate(direct_commodity = !(commodity %in% indirect_commodities)) # create boolean for direct commodity

  return(emissions_df)

}


#' Recode fuel_CO2e Variable
#'
#' Process the fuel_CO2e variable, setting its missing values to 0 and setting
#'  rows with the commodity category for "Biomass and organic waste" to 0 when
#'  zero_emissions_from_biomass is TRUE.
#'
#' @param emissions_df dataframe, created by `create_emissions_df()`
#' @param zero_emissions_from_biomass boolean, whether to treat biomass fuels
#'  as having 0 emissions.
#'
#' @returns dataframe, with same number of rows and columns as emissions_df
#'  provided, but with fuel_CO2e recoded where relevant.
#' @export
recode_fuel_CO2e <- function(emissions_df, zero_emissions_from_biomass) {

  emissions_df <- emissions_df %>%
    mutate(
      fuel_CO2e = case_when(
        commodity_category == "Biomass and organic waste"
        & zero_emissions_from_biomass ~ 0,
        is.na(fuel_CO2e) ~ 0,
        TRUE ~ fuel_CO2e
      )
    )

  return(emissions_df)
}




#' Calculate direct emissions of CO2 gasses
#'
#' @param emissions_df dataframe, created by `create_emissions_df()`
#'
#' @returns dataframe, as input as emissions_df with additional columns:
#'  * CO2_process_released_direct
#'  * CO2_process_captured_direct
#'  * CO2_fuel_released_direct
#'  * CO2_fuel_captured_direct
#' @export
calculate_CO2_direct_emissions <- function(emissions_df) {

  emissions_df <- emissions_df %>%
    mutate(
      common_factors = (
        output
        * proportion_emissions_CO2
        * direct_commodity
      ),
      CO2_process_released_direct = (
        common_factors
        * process_emission
        * emissions_released
      ),
      CO2_process_captured_direct = (
        common_factors
        * process_emission
        * (1 - emissions_released)
      ),
      CO2_fuel_released_direct = -1 * (
        common_factors
        * commodity_produces_emissions
        * (!process_emission)
        * fuel_CO2e
        * emissions_released
      ),
      CO2_fuel_captured_direct = -1 * (
        common_factors
        * commodity_produces_emissions
        * (!process_emission)
        * fuel_CO2e
        * (1-emissions_released)
      )) %>%
    select(!common_factors)

  return(emissions_df)

}



#' Calculate direct emissions of non-CO2 gasses
#'
#' @param emissions_df dataframe, created by `create_emissions_df()`
#'
#' @returns dataframe, as input as emissions_df with additional columns:
#'  * nonCO2_process_released_direct
#'  * nonCO2_process_captured_direct
#'  * nonCO2_fuel_released_direct
#'  * nonCO2_fuel_captured_direct
#' @export
calculate_nonCO2_direct_emissions <- function(emissions_df) {

  emissions_df <- emissions_df %>%
    mutate(
      common_factors = (
        output
        * (1-proportion_emissions_CO2)
        * direct_commodity
        ),
      nonCO2_process_released_direct = (
        common_factors
        * process_emission
      ),
      nonCO2_fuel_released_direct = -1 * (
        common_factors
        * commodity_produces_emissions
        * (!process_emission)
        * fuel_CO2e
      ),
      nonCO2_process_captured_direct = 0,
      nonCO2_fuel_captured_direct = 0) %>%
    select(!common_factors)

  return(emissions_df)

}



# CO2 indirect

#' Calculate indirect emissions of CO2 gasses
#'
#' @param emissions_df dataframe, created by `create_emissions_df()`
#'
#' @returns dataframe, as input as emissions_df with additional columns:
#'  * CO2_process_released_indirect
#'  * CO2_process_captured_indirect
#'  * CO2_fuel_released_indirect
#'  * CO2_fuel_captured_indirect
#' @export
calculate_CO2_indirect_emissions <- function(emissions_df) {

  emissions_df <- emissions_df %>%
    mutate(
      CO2_process_released_indirect = 0,
      CO2_process_captured_indirect = 0,
      CO2_fuel_released_indirect = -1 * (
        commodity_produces_emissions
        * (!process_emission)
        * output
        * proportion_emissions_CO2
        * fuel_CO2e
        * (!direct_commodity)
      ),
      CO2_fuel_captured_indirect = 0)

  return(emissions_df)
}



#' Calculate indirect emissions of nonCO2 gasses
#'
#' @param emissions_df dataframe, created by `create_emissions_df()`
#'
#' @returns dataframe, as input as emissions_df with additional columns:
#'  * nonCO2_process_released_indirect
#'  * nonCO2_process_captured_indirect
#'  * nonCO2_fuel_released_indirect
#'  * nonCO2_fuel_captured_indirect
#' @export
calculate_nonCO2_indirect_emissions <- function(emissions_df) {

  # nonCO2 indirect
  emissions_df <- emissions_df %>%
    mutate(
      nonCO2_process_released_indirect = 0,
      nonCO2_process_captured_indirect = 0,
      nonCO2_fuel_released_indirect = -1 * (
        commodity_produces_emissions
        * (!process_emission)
        * output
        * (1 - proportion_emissions_CO2)
        * fuel_CO2e
        * (!direct_commodity)
      ),
      nonCO2_fuel_captured_indirect = 0
    )

  return(emissions_df)
}




# this aggregates up to the technology level all of the emissions. This is because
# there are emissions for each commodity produced by each tech until this stage.

#' Aggregate each of the emissions type to the technology/year level
#'
#' Sums each type of emissions for each technology in each year. This is done
#'  because until this point, emissions are produced at the commodity level and
#'  there are often many commodities to a single technology.
#'
#' @param emissions_df dataframe, originally created by `create_emissions_df()`
#'  and then having had all required types of emissions calculated by subsequent
#'  functions: `calculate_CO2_direct_emissions`,
#'  `calculate_nonCO2_direct_emissions`,
#'  `calculate_CO2_indirect_emissions` and
#'  `calculate_nonCO2_indirect_emissions`.
#'
#' @returns dataframe, with 16 rows per technology and year (one for each possible
#'  type of emissions). Columns include:
#'  * code
#'  * year
#'  * gas - type of emission: 'CO2' or 'nonCO2'
#'  * source - type of emission: 'process' or 'fuel'
#'  * capture - type of emission: boolean
#'  * location - type of emission: 'direct' or 'indirect'
#'  * CO2e - numeric, amount of emissions per unit of capacity in kilotonnes of
#'   of CO2e.
#' @export
sum_emission_types <- function(emissions_df) {

  emissions_cols <- c(
    "CO2_process_released_direct",
    "CO2_process_captured_direct",
    "CO2_fuel_released_direct",
    "CO2_fuel_captured_direct",

    "nonCO2_process_released_direct",
    "nonCO2_process_captured_direct",
    "nonCO2_fuel_released_direct",
    "nonCO2_fuel_captured_direct",

    "CO2_process_released_indirect",
    "CO2_process_captured_indirect",
    "CO2_fuel_released_indirect",
    "CO2_fuel_captured_indirect",

    "nonCO2_process_released_indirect",
    "nonCO2_process_captured_indirect",
    "nonCO2_fuel_released_indirect",
    "nonCO2_fuel_captured_indirect"
  )


  # work out emissions from each gas, source, and if captured or not
  aggregated_emissions <- emissions_df %>%
    group_by(code, year) %>%
    summarise_at(emissions_cols, sum)

  # make table long so each type of emissions has its own row
  aggregated_emissions %<>%
    pivot_longer(cols = all_of(emissions_cols),
                 names_to = c("gas", "source", "capture", "location"),
                 names_pattern = "(.*)_(.*)_(.*)_(.*)",
                 values_to = "CO2e") %>%
    mutate(capture = capture == "captured") # make captured variable a boolean

  return(aggregated_emissions)
}



#' Calculate total emissions for each technology in each year for all relevant
#' types of emissions
#'
#' @param aggregated_emissions dataframe as produced by `sum_emission_types()`.
#' @param gas_included string or character vector for the gas types to include.
#'  Allowed values are 'CO2' or 'nonCO2'.
#' @param source_included string or character vector for the gas types to include.
#'  Allowed values are 'fuel' or 'process'.
#' @param capture_included boolean or boolean vector for the gas types to include.
#' @param location_included string or character vector for the gas types to include.
#'  Allowed values are 'direct' or 'indirect'.
#'
#' @returns dataframe with one row for each technology in each year. Columns are:
#'  * code
#'  * year
#'  * CO2e - amount of CO2e emitted (kt) per unit of used capacity
#' @export
get_total_emissions <- function(aggregated_emissions,
                                gas_included,
                                source_included,
                                capture_included,
                                location_included) {

  # remove the emission types that aren't included, then sum what's left to get total
  # emissions
  total_emissions <- aggregated_emissions %>%
    filter(gas %in% gas_included,
           source %in% source_included,
           capture %in% capture_included,
           location %in% location_included) %>%
    group_by(code, year) %>%
    summarise(CO2e = sum(CO2e),
              .groups = "drop")

  return(total_emissions)
}



#' This function returns net emissions outputed per used capacity of a technology in kilotonnes of CO2e
net_emissions <- function(technology_code, gas = NULL, year = 2020, .data = data)
{
  # We define net emissions as all emissions before capture - captured emissions
  if(hasArg(gas)){
    emissions_before_capture <- get_emissions(technology_code, year, gas = gas,
                                              .data = .data, zero_emissions_from_biomass = TRUE)
    emissions_after_capture <- get_emissions(technology_code, year, gas = gas, capture = TRUE,
                                             .data = .data, zero_emissions_from_biomass = FALSE)
  } else {
    emissions_before_capture <- get_emissions(technology_code, year,
                                              .data = .data, zero_emissions_from_biomass = TRUE)
    emissions_after_capture <- get_emissions(technology_code, year, capture = TRUE,
                                             .data = .data, zero_emissions_from_biomass = FALSE)
  }

  return(emissions_before_capture - emissions_after_capture)
}



